# Generated by Django 5.1.6 on 2025-04-01 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chat',
            name='unique_chat_per_offer_and_participants',
        ),
    ]
