# Generated by Django 5.1.6 on 2025-02-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offers',
            field=models.ManyToManyField(related_name='categories', to='base.offer'),
        ),
    ]
