# Generated by Django 5.1.6 on 2025-02-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/static//images/avatar.svg', null=True, upload_to=''),
        ),
    ]
