# Generated by Django 5.1.6 on 2025-02-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_offer_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='user',
            new_name='creator',
        ),
    ]
