# Generated by Django 5.1.6 on 2025-02-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='D:\\Wojtek\\dzielimysie.tu\\dzielimysie_tu\\static\\images\\images/default_avatar.png', null=True, upload_to=''),
        ),
    ]
