# Generated by Django 5.1.6 on 2025-02-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
