# Generated by Django 5.1.6 on 2025-02-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legal_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
