# Generated by Django 5.1.6 on 2025-02-28 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_user_legal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='legal_name',
        ),
    ]
