# Generated by Django 5.1.6 on 2025-02-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
