# Generated by Django 5.1.6 on 2025-03-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='offer_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='place',
            field=models.CharField(max_length=200),
        ),
    ]
