# Generated by Django 5.1.6 on 2025-03-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_category_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offers',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='base.offer'),
        ),
    ]
