# Generated by Django 5.1.6 on 2025-03-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_category_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='place',
        ),
        migrations.AlterField(
            model_name='category',
            name='offers',
            field=models.ManyToManyField(related_name='categories', to='base.offer'),
        ),
    ]
