# Generated by Django 5.1.6 on 2025-03-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_offer_photos_remove_offer_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='offer_photos/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='place',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='category',
            name='offers',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='base.offer'),
        ),
    ]
