# Generated by Django 5.1.6 on 2025-03-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_offer_photos_offer_place_alter_category_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='offers',
            field=models.ManyToManyField(related_name='offers', to='base.offer'),
        ),
    ]
