# Generated by Django 5.1.6 on 2025-03-01 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_category_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='offers',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='photos',
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='offer_photos/')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.offer')),
            ],
        ),
    ]
