# Generated by Django 5.1.6 on 2025-03-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_photo_delete_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='offer_photos/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
