# Generated by Django 5.1.6 on 2025-03-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_offer_photos_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
