# Generated by Django 5.1.6 on 2025-03-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_user_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='creator_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
