# Generated by Django 5.1.6 on 2025-03-01 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_offer_creator_name_offer_email_offer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='photos',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='offer_photos/')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.offer')),
            ],
        ),
    ]
