# Generated by Django 5.1.6 on 2025-03-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_offer_photos_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='email',
            new_name='creator_email',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='phone',
            new_name='creator_phone',
        ),
    ]
