# Generated by Django 5.1.6 on 2025-03-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_rename_email_offer_creator_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='offer',
            new_name='related_offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='photos',
            field=models.ManyToManyField(to='base.photo'),
        ),
    ]
