# Generated by Django 5.1.6 on 2025-03-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_rename_offer_photo_related_offer_offer_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='related_offer',
            new_name='offer',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='photos',
        ),
    ]
