# Generated by Django 5.1.6 on 2025-03-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_user_first_name_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
