# Generated by Django 5.1.6 on 2025-03-04 09:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_offer_place_follow_offer_follow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_offers',
            field=models.ManyToManyField(related_name='followers', through='base.Follow_offer', to='base.offer'),
        ),
        migrations.AddField(
            model_name='user',
            name='following_users',
            field=models.ManyToManyField(related_name='followers', through='base.Follow_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
