# Generated by Django 5.1.6 on 2025-03-04 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_user_followed_offers_user_following_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed_offers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_users',
        ),
    ]
