# Generated by Django 5.1.6 on 2025-03-04 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_remove_user_followed_offers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
