# Generated by Django 5.1.6 on 2025-03-04 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_offer_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='offer_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
