# Generated by Django 5.1.6 on 2025-03-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_user_followers_alter_offer_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_message_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='new_offer_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='price_change_notification',
            field=models.BooleanField(default=False),
        ),
    ]
