# Generated by Django 5.1.6 on 2025-03-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_user_new_message_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('waiting', 'Oczekujące'), ('in_progress', 'W realizacji'), ('cancelled', 'Anulowane'), ('finished', 'Zakończone')], default='waiting', max_length=20),
        ),
    ]
