# Generated by Django 5.1.6 on 2025-03-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_offer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
    ]
