# Generated by Django 5.1.6 on 2025-03-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_remove_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('waiting', 'Oczekujące'), ('in_progress', 'W realizacji'), ('cancelled', 'Anulowane'), ('finished', 'Zakończone')], default='waiting', max_length=20),
        ),
    ]
