# Generated by Django 5.1.6 on 2025-03-06 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('waiting', 'Oczekujące'), ('pending', 'Do akceptacji'), ('in_progress', 'W realizacji'), ('cancelled', 'Anulowane'), ('finished', 'Zakończone')], default='waiting', max_length=20),
        ),
        migrations.CreateModel(
            name='Take_offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.offer')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
