# Generated by Django 5.1.6 on 2025-03-06 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_offer_status_take_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='take_offer',
            old_name='created',
            new_name='time',
        ),
    ]
