# Generated by Django 5.1.6 on 2025-03-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_rename_created_take_offer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='take_offer',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
