# Generated by Django 5.1.6 on 2025-03-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_take_offer_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='take_offer',
            name='title',
        ),
        migrations.AlterField(
            model_name='take_offer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_offer_set', to='base.offer'),
        ),
    ]
