# Generated by Django 5.1.6 on 2025-03-06 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_remove_take_offer_title_alter_take_offer_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take_offer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.offer'),
        ),
    ]
