# Generated by Django 5.1.6 on 2025-03-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_take_offer_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='take_offer',
            name='status',
            field=models.CharField(choices=[('waiting', 'Oczekujące'), ('accepted', 'Zaakceptowane'), ('rejected', 'Odrzucone'), ('cancelled', 'Anulowane'), ('finished', 'Zakończone')], default='waiting', max_length=20),
        ),
    ]
