# Generated by Django 5.1.6 on 2025-03-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_take_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('waiting', 'Oczekujące'), ('pending', 'Zgłoszenia'), ('in_progress', 'W realizacji'), ('cancelled', 'Anulowane'), ('finished', 'Zakończone')], default='waiting', max_length=20),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
