# Generated by Django 5.1.6 on 2025-03-25 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_alter_offer_status_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opinions_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='opinions_overall',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='opinions_sum',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='base.offer')),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='opinions',
            field=models.ManyToManyField(blank=True, related_name='user_opinions', to='base.opinion'),
        ),
    ]
