# Generated by Django 5.1.6 on 2025-03-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_user_opinions_count_user_opinions_overall_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opinion',
            old_name='time',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='text',
            field=models.TextField(max_length=100),
        ),
    ]
