# Generated by Django 5.1.6 on 2025-03-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_rename_time_opinion_date_alter_opinion_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='opinions_overall',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='opinions_sum',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5),
        ),
    ]
