# Generated by Django 5.1.6 on 2025-03-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_alter_user_opinions_overall_alter_user_opinions_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='creator_to_taker_opinion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='opinion',
            name='taker_to_creator_opinion',
            field=models.BooleanField(default=False),
        ),
    ]
