# Generated by Django 5.1.6 on 2025-03-27 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_opinion_creator_to_taker_opinion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='take_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='base.take_offer'),
        ),
    ]
