# Generated by Django 5.1.6 on 2025-03-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_alter_opinion_take_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='creator_to_taker_opinion',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='take_offer',
        ),
        migrations.RemoveField(
            model_name='opinion',
            name='taker_to_creator_opinion',
        ),
        migrations.AddField(
            model_name='take_offer',
            name='creator_to_taker_opinion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='take_offer',
            name='taker_to_creator_opinion',
            field=models.BooleanField(default=False),
        ),
    ]
