# Generated by Django 5.1.6 on 2025-04-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_remove_opinion_creator_to_taker_opinion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
