# Generated by Django 5.1.6 on 2025-05-27 21:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_opinion_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='opinion',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
